### ISSUE TITLE
Consider adding meta tag to zoom out in mobile devices

### ISSUE THREAD

**Issue by epintos** [Wolox/rails-bootstrap#15]
@SKOLZ Consider adding `<meta name="viewport" content="width=device-width, initial-scale=1.0">`

**Comment by epintos** [comment]
@SKOLZ

**Comment by SKOLZ** [comment]
@epintos I thought we had the "fake responsive" meta tag which makes the page look really small and allows the user to zoom in. This is not ideal but It's a basic solution for pages that don't have responsiveness implemented. What should we do?
- Add the responsive meta tag?
- Add the fake responsive zoom out meta tag?

**Comment by epintos** [comment]
@SKOLZ I'm not sure which one is in the app. Which one you recommend?

**Comment by holywyvern** [comment]
While it was probably a good idea in 2017, we decide to move the bootstrap to an API only version, so I'm closing this issue.
