### ISSUE TITLE
Error en el Readme

### ISSUE THREAD

**Issue by NicoBuch** [Wolox/rails-bootstrap#17]
En la linea 120 dice CREATE DATATABASE "your-database" owner "your-username";

`DATATABASE` ... 
Parece RATATA 

![](https://i.imgflip.com/14659k.jpg)

**Comment by NicoBuch** [comment]
Otra cosa: Lo que tenes que instalar de redis se llama tcl8.5  no tlc8.5

**Comment by epintos** [comment]
Thanks @NicoBuch! All typos fixed
