### ISSUE TITLE
AWS deploy -> Bundle: Command not found.

### ISSUE THREAD

**Issue by NicoBuch** [Wolox/rails-bootstrap#18]
Following the Documentation, and trying to deploy to an EC2 instance of AWS, when finally executing bundle exec cap production deploy, an error occured: `rbenv: bundle: command not found`

You must be missing a place where to run gem install bundler in ec2

**Comment by epintos** [comment]
@NicoBuch I will check this next time I do a new kickoff. It was working the last time I did it
