### ISSUE TITLE
Rack attack requests per second

### ISSUE THREAD

**Issue by alebian** [Wolox/rails-bootstrap#43]
Why don't we set a default value for this, say 5 requests per second

https://github.com/Wolox/rails-bootstrap/blob/275c3be4d534b9f928bf8ff6bc105b4059df1e0a/config/initializers/rack-attack.rb#L42

Also we can set exponential backoff for login by default, [more datails](https://github.com/kickstarter/rack-attack/wiki/Advanced-Configuration)

**Comment by mishuagopian** [comment]
Maybe 5 requests per second will be short, but we can set a default value for this @alebian

**Comment by alebian** [comment]
@mishuagopian this is good i think
```
  throttle('req/ip', limit: 5, period: 1.second) do |req|
    req.ip unless req.path.start_with?('/assets')
  end
```

**Comment by alebian** [comment]
Also we must define this in order to work in Rails 5

`Rack::Attack.cache.store = ActiveSupport::Cache::MemoryStore.new`

**Comment by hdf1986** [comment]
Pr merged

**Comment by mishuagopian** [comment]
👏
