### ISSUE TITLE
Remove rails_12factor dependency

### ISSUE THREAD

**Issue by alexanderadam** [Wolox/rails-bootstrap#67]
I just saw [this](https://github.com/Wolox/rails-bootstrap/blob/master/Gemfile#L146) by accident and thought you might want to know that [it's not necessary on Rails 5 anymore](https://github.com/heroku/rails_12factor#new-rails-5-apps).

Have a wonderful new year!

**Comment by tferrerm** [comment]
Solved in #83 (check [line 95 of this file](https://github.com/Wolox/rails-bootstrap/pull/83/files#diff-d09ea66f8227784ff4393d88a19836f321c915ae10031d16c93d67e6283ab55f))

**Comment by alexanderadam** [comment]
Wow, I totally forgot about this issue from January 2019.
